#!/bin/bash

shopt -s dotglob

file_action() {
    link_path="$PWD/$1"
    target=$HOME/${1##*/}
    echo "$link_path => $target"

    if [ -e $target -a ! "$target" -ef "$link_path" ]; then
        read -n1 -p "$target already exists. diff, remove, backup, ignore, cancel? [d/r/b/i/c] " delete_file
        echo
        case $delete_file in
            r)
                rm -r -- "$target"
                file_action "$1"
            ;;
            d)
                vimdiff -R "$target" "$link_path"
                file_action "$1"
            ;;
            b)
                mv -i -- "$target"{,.bak}
                file_action "$1"
            ;;
            c)
                exit 0
            ;;
        esac
    elif [ ! "$target" -ef "$link_path" ]; then
        ln -fs -- "$link_path" "$target"
    fi
}

for f in home/*; do
    file_action "$f"
done
